# Generated by Django 6.0.5 on 2026-05-28 14:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="max_farms",
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name="tenant",
            name="max_users",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="tenant",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("SUSPENDED", "Suspended"),
                    ("EXPIRED", "Expired"),
                ],
                default="ACTIVE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="subscription_end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="subscription_start",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="currency_symbol",
            field=models.CharField(default="UGX", max_length=5),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="date_format",
            field=models.CharField(default="Y-m-d", max_length=20),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="email_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="tenant_logos/"),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="primary_color",
            field=models.CharField(default="#2E7D32", max_length=7),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="secondary_color",
            field=models.CharField(default="#FF8F00", max_length=7),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="sms_notifications",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="tenant_code",
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AddIndex(
            model_name="tenant",
            index=models.Index(fields=["slug"], name="tenants_ten_slug_63daca_idx"),
        ),
        migrations.AddIndex(
            model_name="tenant",
            index=models.Index(
                fields=["tenant_code"], name="tenants_ten_tenant__62c292_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tenant",
            index=models.Index(fields=["status"], name="tenants_ten_status_e7eaee_idx"),
        ),
    ]
