# Generated by Django 6.0.5 on 2026-06-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0002_alter_cart_options_alter_order_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("DAY_OLD_CHICKS", "Day Old Chicks"),
                    ("FEED", "Feed"),
                    ("GLUCOSE", "Glucose"),
                    ("MEDICINE", "Medicine/Vaccines"),
                    ("EQUIPMENT", "Equipment"),
                    ("ACCESSORIES", "Accessories"),
                    ("EGGS", "Eggs"),
                    ("MEAT", "Meat"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=20,
            ),
        ),
    ]
