# Generated by Django 6.0.5 on 2026-05-28 14:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_options_userprofile_created_at_and_more"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("tenants", "0002_tenant_max_farms_tenant_max_users_tenant_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="last_login_ip",
        ),
        migrations.AddField(
            model_name="user",
            name="last_login_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="locked_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="login_attempts",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="currency",
            field=models.CharField(default="UGX", max_length=3),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_login_user_agent",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="notification_preferences",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="timezone",
            field=models.CharField(default="Africa/Kampala", max_length=50),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                db_index=True,
                max_length=15,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9]{10,15}$", "Enter a valid phone number"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("sw", "Swahili"), ("lg", "Luganda")],
                default="en",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="profile_photo",
            field=models.ImageField(blank=True, null=True, upload_to="profiles/%Y/%m/"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["phone_number"], name="accounts_us_phone_n_613c4a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["role"], name="accounts_us_role_1fa9a5_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["tenant"], name="accounts_us_tenant__b29105_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["district"], name="accounts_us_distric_bf1127_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["language"], name="accounts_us_languag_bf8acf_idx"
            ),
        ),
    ]
