# Generated by Django 6.0.5 on 2026-05-31 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0003_remove_userprofile_last_login_ip_user_last_login_ip_and_more",
        ),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="userprofile",
            name="accounts_us_distric_bf1127_idx",
        ),
        migrations.RemoveIndex(
            model_name="userprofile",
            name="accounts_us_languag_bf8acf_idx",
        ),
        migrations.AddField(
            model_name="user",
            name="assigned_districts",
            field=models.TextField(
                blank=True, help_text="Comma-separated list of districts"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="license_number",
            field=models.CharField(
                blank=True, help_text="Professional license number", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="organization_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="user",
            name="organization_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("COOPERATIVE", "Cooperative"),
                    ("AGRIBUSINESS", "Agribusiness"),
                    ("NGO", "Non-Profit Organization"),
                    ("GOVERNMENT", "Government Agency"),
                    ("RESEARCH", "Research Institution"),
                    ("OTHER", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="registration_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="specialization",
            field=models.CharField(
                blank=True,
                help_text="e.g., Poultry Vet, Livestock Extension",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="tax_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="website",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="years_experience",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("FARMER", "Farmer"),
                    ("CUSTOMER", "Customer"),
                    ("SUPPLIER", "Supplier"),
                    ("TRAINER", "Trainer"),
                    ("FIELD_OFFICER", "Field Officer (Vet/Extension Worker)"),
                    ("ORGANIZATION", "Organization"),
                    ("ADMIN", "Admin"),
                    ("SUPER_ADMIN", "Super Admin"),
                ],
                default="FARMER",
                max_length=20,
            ),
        ),
    ]
