# Generated by Django 6.0.5 on 2026-06-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_userprofile_accounts_us_distric_bf1127_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="organization_join_code",
            field=models.CharField(
                blank=True,
                help_text="Tenant code to join an organization",
                max_length=20,
            ),
        ),
    ]
