# Generated by Django 6.0.5 on 2026-05-28 13:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Farm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("farm_name", models.CharField(max_length=100)),
                (
                    "farm_type",
                    models.CharField(
                        choices=[
                            ("LAYERS", "Layers"),
                            ("BROILERS", "Broilers"),
                            ("BREEDERS", "Breeders"),
                            ("MIXED", "Mixed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("district", models.CharField(max_length=100)),
                ("village", models.CharField(max_length=100)),
                (
                    "size_acres",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FlockBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_name", models.CharField(max_length=100)),
                (
                    "bird_type",
                    models.CharField(
                        choices=[
                            ("LAYERS", "Layers"),
                            ("BROILERS", "Broilers"),
                            ("DAY_OLD", "Day Old Chicks"),
                            ("GROWERS", "Growers"),
                            ("BREEDERS", "Breeders"),
                        ],
                        max_length=20,
                    ),
                ),
                ("breed", models.CharField(max_length=100)),
                ("quantity", models.IntegerField()),
                ("start_date", models.DateField()),
                ("expected_end_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("CULLED", "Culled"),
                            ("DEPLETED", "Depleted"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="farm.farm"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("FEED", "Feed"),
                            ("VACCINES", "Vaccines"),
                            ("MEDICATION", "Medication"),
                            ("LABOR", "Labor"),
                            ("UTILITIES", "Utilities"),
                            ("MAINTENANCE", "Maintenance"),
                            ("TRANSPORT", "Transport"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("description", models.TextField()),
                ("expense_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "receipt",
                    models.FileField(blank=True, null=True, upload_to="receipts/"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant"
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="farm.farm",
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="farm.flockbatch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="House",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("capacity", models.IntegerField()),
                ("current_population", models.IntegerField(default=0)),
                (
                    "house_type",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open House"),
                            ("CLOSED", "Closed House"),
                            ("BATTERY", "Battery Cages"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="houses",
                        to="farm.farm",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="flockbatch",
            name="house",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="farm.house"
            ),
        ),
        migrations.CreateModel(
            name="VaccinationRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vaccine_name", models.CharField(max_length=100)),
                ("scheduled_date", models.DateField()),
                ("administered_date", models.DateField(blank=True, null=True)),
                ("administered_by", models.CharField(blank=True, max_length=100)),
                (
                    "cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("COMPLETED", "Completed"),
                            ("MISSED", "Missed"),
                        ],
                        default="SCHEDULED",
                        max_length=20,
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vaccinations",
                        to="farm.flockbatch",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DailyRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("mortality", models.IntegerField(default=0)),
                (
                    "feed_used_kg",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "water_used_liters",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("eggs_collected", models.IntegerField(default=0)),
                (
                    "avg_weight_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant"
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_records",
                        to="farm.flockbatch",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("batch", "date")},
            },
        ),
    ]
