# Generated by Django 6.0.5 on 2026-06-01 13:02

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0001_initial"),
        ("tenants", "0002_tenant_max_farms_tenant_max_users_tenant_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FlockVaccinationSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_date", models.DateField()),
                ("due_week", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("COMPLETED", "Completed"),
                            ("OVERDUE", "Overdue"),
                            ("SKIPPED", "Skipped"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("completed_date", models.DateField(blank=True, null=True)),
                ("notification_sent", models.BooleanField(default=False)),
                ("reminder_sent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["scheduled_date"],
            },
        ),
        migrations.CreateModel(
            name="VaccinationSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bird_type",
                    models.CharField(
                        choices=[
                            ("LAYERS", "Layers"),
                            ("BROILERS", "Broilers"),
                            ("KUROILERS", "Kuroilers"),
                            ("BREEDERS", "Breeders"),
                        ],
                        max_length=20,
                    ),
                ),
                ("week_number", models.IntegerField()),
                ("vaccine_name", models.CharField(max_length=100)),
                (
                    "vaccine_type",
                    models.CharField(
                        choices=[
                            ("NEWCASTLE", "Newcastle Disease (ND)"),
                            ("INFECTIOUS_BRONCHITIS", "Infectious Bronchitis (IB)"),
                            ("GUMBORO", "Gumboro (IBD)"),
                            ("FOWL_POX", "Fowl Pox (FP)"),
                            ("SALMONELLA", "Salmonella"),
                            ("COCCIDIOSIS", "Coccidiosis"),
                            ("MAREKS", "Marek's Disease"),
                            ("EGG_DROP_SYNDROME", "Egg Drop Syndrome"),
                            ("OTHER", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("administration_method", models.CharField(max_length=50)),
                ("dosage", models.CharField(blank=True, max_length=100)),
                ("is_required", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["bird_type", "week_number"],
            },
        ),
        migrations.RemoveField(
            model_name="expense",
            name="batch",
        ),
        migrations.RemoveField(
            model_name="expense",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="expense",
            name="farm",
        ),
        migrations.RemoveField(
            model_name="expense",
            name="tenant",
        ),
        migrations.AlterModelOptions(
            name="farm",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="flockbatch",
            options={"ordering": ["-start_date"]},
        ),
        migrations.AlterModelOptions(
            name="house",
            options={"ordering": ["house_number"]},
        ),
        migrations.AlterModelOptions(
            name="vaccinationrecord",
            options={"ordering": ["scheduled_date"]},
        ),
        migrations.RenameField(
            model_name="dailyrecord",
            old_name="feed_used_kg",
            new_name="feed_consumed_kg",
        ),
        migrations.RenameField(
            model_name="dailyrecord",
            old_name="water_used_liters",
            new_name="water_consumed_liters",
        ),
        migrations.RenameField(
            model_name="vaccinationrecord",
            old_name="cost",
            new_name="cost_per_dose",
        ),
        migrations.RemoveField(
            model_name="dailyrecord",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="flockbatch",
            name="quantity",
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="administered_by",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="alerts_generated",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="ammonia_level",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="birds_added",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="birds_culled",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="birds_sold",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="birds_sold_avg_weight",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="birds_sold_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="closing_bird_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="deworming_done",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="deworming_product",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="disease_symptoms",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="dosage",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="drug_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="egg_production_percent",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="eggs_broken",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="eggs_cracked",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="eggs_dirty",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="eggs_extra_large",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="eggs_large",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="eggs_medium",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="eggs_saleable",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="eggs_small",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="eggs_sold_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="farmer_observations",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="feed_conversion_ratio",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="feed_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="feed_given_kg",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="feed_remaining_kg",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="feed_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("STARTER", "Starter Feed (0-4 weeks)"),
                    ("GROWER", "Grower Feed (4-16 weeks)"),
                    ("FINISHER", "Finisher Feed (16+ weeks)"),
                    ("LAYER_MASH", "Layer Mash"),
                    ("BROILER_STARTER", "Broiler Starter"),
                    ("BROILER_FINISHER", "Broiler Finisher"),
                    ("CHICK_MASH", "Chick Mash"),
                    ("OTHER", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="health_status",
            field=models.CharField(
                choices=[
                    ("GOOD", "Good - No Issues"),
                    ("WATCH", "Watch - Monitor Closely"),
                    ("MINOR", "Minor Illness"),
                    ("SERIOUS", "Serious Illness"),
                    ("OUTBREAK", "Disease Outbreak"),
                ],
                default="GOOD",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="humidity_percent",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="labour_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="litter_condition",
            field=models.CharField(
                choices=[
                    ("DRY", "Dry - Good"),
                    ("DAMP", "Damp - Needs Attention"),
                    ("WET", "Wet - Change Required"),
                    ("POOR", "Poor - Immediate Action"),
                ],
                default="DRY",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="max_weight_kg",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="medication_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="min_weight_kg",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="opening_bird_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="other_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="price_per_bird",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="price_per_egg",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="price_per_kg",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="price_per_tray",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="purpose",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="recommendations",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="recorded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="sales_revenue",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="signs_observed",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="temperature_c",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="total_expenses",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="transport_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="trays_sold",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="treatments_given",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="utilities_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="vaccine_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="ventilation_status",
            field=models.CharField(
                choices=[
                    ("GOOD", "Good"),
                    ("POOR", "Poor"),
                    ("EXCESSIVE", "Excessive"),
                    ("INSUFFICIENT", "Insufficient"),
                ],
                default="GOOD",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="veterinary_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="veterinary_visit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="water_provided_liters",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="weight_gain_kg",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="weight_sample_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="withdrawal_period_days",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="farm",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="farm",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name="farm",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_farms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="established_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="farm",
            name="gps_coordinates",
            field=models.CharField(
                blank=True, help_text="Latitude, Longitude", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="farm",
            name="parish",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="farm",
            name="registration_number",
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name="flockbatch",
            name="batch_number",
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name="flockbatch",
            name="cost_per_bird",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="flockbatch",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_flocks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="flockbatch",
            name="current_quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="flockbatch",
            name="expected_egg_production",
            field=models.IntegerField(default=0, help_text="Expected eggs per day"),
        ),
        migrations.AddField(
            model_name="flockbatch",
            name="expected_feed_conversion",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="flockbatch",
            name="expected_mortality_rate",
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5),
        ),
        migrations.AddField(
            model_name="flockbatch",
            name="initial_quantity",
            field=models.IntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AddField(
            model_name="flockbatch",
            name="source",
            field=models.CharField(
                blank=True, help_text="Where birds were purchased from", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="flockbatch",
            name="total_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="flockbatch",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="house",
            name="area_sqft",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="house",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="house",
            name="has_automated_drinker",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="house",
            name="has_automated_feeder",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="house",
            name="has_heating",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="house",
            name="has_lighting",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="house",
            name="has_ventilation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="house",
            name="height_m",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="house",
            name="house_number",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="house",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="house",
            name="length_m",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="house",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="house",
            name="width_m",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="vaccinationrecord",
            name="administration_method",
            field=models.CharField(
                choices=[
                    ("DRINKING_WATER", "Drinking Water"),
                    ("SPRAY", "Spray"),
                    ("INJECTION", "Injection"),
                    ("EYE_DROP", "Eye Drop"),
                    ("WING_WEB", "Wing Web"),
                ],
                default="DRINKING_WATER",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="vaccinationrecord",
            name="batch_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="vaccinationrecord",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vaccinationrecord",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="vaccinationrecord",
            name="dosage",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="vaccinationrecord",
            name="manufacturer",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="vaccinationrecord",
            name="quantity_used",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="vaccinationrecord",
            name="reaction_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="vaccinationrecord",
            name="total_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="vaccinationrecord",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="vaccinationrecord",
            name="vaccine_type",
            field=models.CharField(
                choices=[
                    ("NEWCASTLE", "Newcastle Disease (ND)"),
                    ("INFECTIOUS_BRONCHITIS", "Infectious Bronchitis (IB)"),
                    ("GUMBORO", "Gumboro (IBD)"),
                    ("FOWL_POX", "Fowl Pox (FP)"),
                    ("SALMONELLA", "Salmonella"),
                    ("COCCIDIOSIS", "Coccidiosis"),
                    ("MAREKS", "Marek's Disease"),
                    ("EGG_DROP_SYNDROME", "Egg Drop Syndrome"),
                    ("OTHER", "Other"),
                ],
                default=django.utils.timezone.now,
                max_length=30,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="dailyrecord",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_records",
                to="tenants.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="farm_type",
            field=models.CharField(
                choices=[
                    ("LAYERS", "Layers"),
                    ("BROILERS", "Broilers"),
                    ("BREEDERS", "Breeders"),
                    ("MIXED", "Mixed"),
                    ("FREE_RANGE", "Free Range"),
                ],
                default="LAYERS",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="farms",
                to="tenants.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="flockbatch",
            name="bird_type",
            field=models.CharField(
                choices=[
                    ("LAYERS", "Layers"),
                    ("BROILERS", "Broilers"),
                    ("DAY_OLD", "Day Old Chicks"),
                    ("GROWERS", "Growers"),
                    ("BREEDERS", "Breeders"),
                    ("KUROILER", "Kuroiler"),
                    ("POINTS", "Point of Lay"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="flockbatch",
            name="breed",
            field=models.CharField(
                choices=[
                    ("ISA_BROWN", "ISA Brown"),
                    ("BOVANS_BROWN", "Bovans Brown"),
                    ("HYLINE", "Hy-Line"),
                    ("LOHMANN", "Lohmann"),
                    ("ROSS", "Ross"),
                    ("COBB", "Cobb"),
                    ("KUROILER", "Kuroiler"),
                    ("RAINBOW", "Rainbow Rooster"),
                    ("LOCAL", "Local Breed"),
                    ("OTHER", "Other"),
                ],
                default="ISA_BROWN",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="flockbatch",
            name="farm",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flock_batches",
                to="farm.farm",
            ),
        ),
        migrations.AlterField(
            model_name="flockbatch",
            name="house",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flock_batches",
                to="farm.house",
            ),
        ),
        migrations.AlterField(
            model_name="flockbatch",
            name="status",
            field=models.CharField(
                choices=[
                    ("PLANNED", "Planned"),
                    ("ACTIVE", "Active"),
                    ("COMPLETED", "Completed"),
                    ("CULLED", "Culled"),
                    ("DEPLETED", "Depleted"),
                    ("SICK", "Sick/Quarantined"),
                ],
                default="PLANNED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="flockbatch",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flock_batches",
                to="tenants.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="capacity",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="house_type",
            field=models.CharField(
                choices=[
                    ("OPEN", "Open House"),
                    ("CLOSED", "Closed House"),
                    ("BATTERY", "Battery Cages"),
                    ("DEEP_LITTER", "Deep Litter"),
                ],
                default="OPEN",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="houses",
                to="tenants.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="vaccinationrecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("SCHEDULED", "Scheduled"),
                    ("COMPLETED", "Completed"),
                    ("MISSED", "Missed"),
                    ("RESCHEDULED", "Rescheduled"),
                ],
                default="SCHEDULED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="vaccinationrecord",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vaccinations",
                to="tenants.tenant",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="farm",
            unique_together={("tenant", "farm_name")},
        ),
        migrations.AlterUniqueTogether(
            name="house",
            unique_together={("farm", "house_number")},
        ),
        migrations.AddIndex(
            model_name="dailyrecord",
            index=models.Index(fields=["date"], name="farm_dailyr_date_f39318_idx"),
        ),
        migrations.AddIndex(
            model_name="dailyrecord",
            index=models.Index(
                fields=["batch", "date"], name="farm_dailyr_batch_i_087095_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="flockbatch",
            index=models.Index(fields=["status"], name="farm_flockb_status_d7bb7e_idx"),
        ),
        migrations.AddIndex(
            model_name="flockbatch",
            index=models.Index(
                fields=["batch_number"], name="farm_flockb_batch_n_b30039_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="flockbatch",
            index=models.Index(
                fields=["start_date"], name="farm_flockb_start_d_b06c0e_idx"
            ),
        ),
        migrations.AddField(
            model_name="flockvaccinationschedule",
            name="batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vaccination_schedule",
                to="farm.flockbatch",
            ),
        ),
        migrations.AddField(
            model_name="flockvaccinationschedule",
            name="vaccination_record",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="farm.vaccinationrecord",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="vaccinationschedule",
            unique_together={("bird_type", "week_number", "vaccine_type")},
        ),
        migrations.AddField(
            model_name="flockvaccinationschedule",
            name="vaccine_template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="farm.vaccinationschedule",
            ),
        ),
        migrations.DeleteModel(
            name="Expense",
        ),
        migrations.AlterUniqueTogether(
            name="flockvaccinationschedule",
            unique_together={("batch", "vaccine_template")},
        ),
    ]
