# Generated by Django 6.0.5 on 2026-06-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0002_flockvaccinationschedule_vaccinationschedule_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="house",
            name="current_population",
        ),
        migrations.AlterField(
            model_name="flockbatch",
            name="status",
            field=models.CharField(
                choices=[
                    ("PLANNED", "Planned"),
                    ("ACTIVE", "Active"),
                    ("COMPLETED", "Completed"),
                    ("CULLED", "Culled"),
                    ("DEPLETED", "Depleted"),
                    ("SICK", "Sick/Quarantined"),
                ],
                default="ACTIVE",
                max_length=20,
            ),
        ),
    ]
