# Generated by Django 6.0.5 on 2026-06-02 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0003_remove_house_current_population_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vaccinationrecord",
            name="vaccine_name",
        ),
    ]
