# Generated by Django 6.0.5 on 2026-06-03 10:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0004_remove_vaccinationrecord_vaccine_name"),
        ("tenants", "0002_tenant_max_farms_tenant_max_users_tenant_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("HIGH_MORTALITY", "High Mortality"),
                            ("DISEASE_OUTBREAK", "Disease Outbreak"),
                            ("SYMPTOM_ALERT", "Symptom Alert"),
                            ("TREATMENT_DUE", "Treatment Due"),
                            ("FOLLOW_UP", "Follow-up Required"),
                            ("VET_VISIT", "Veterinary Visit Recommended"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("recommended_action", models.TextField(blank=True)),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_alerts",
                        to="farm.flockbatch",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HealthRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("record_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "health_status",
                    models.CharField(
                        choices=[
                            ("EXCELLENT", "Excellent - No Issues"),
                            ("GOOD", "Good - Minor Observations"),
                            ("FAIR", "Fair - Needs Attention"),
                            ("POOR", "Poor - Health Issues"),
                            ("CRITICAL", "Critical - Immediate Action Required"),
                        ],
                        default="GOOD",
                        max_length=20,
                    ),
                ),
                (
                    "disease_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("RESPIRATORY", "Respiratory Disease"),
                            ("DIGESTIVE", "Digestive Issue"),
                            ("EGG_DROP", "Egg Drop Syndrome"),
                            ("LAMENESS", "Lameness/Leg Issues"),
                            ("SKIN", "Skin/Feather Issues"),
                            ("EYE", "Eye Infection"),
                            ("NEWCASTLE", "Newcastle Disease"),
                            ("GUMBORO", "Gumboro (IBD)"),
                            ("FOWL_POX", "Fowl Pox"),
                            ("COCCIDIOSIS", "Coccidiosis"),
                            ("SALMONELLA", "Salmonella"),
                            ("AVIAN_FLU", "Avian Influenza"),
                            ("UNKNOWN", "Unknown/Under Investigation"),
                            ("OTHER", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "symptoms",
                    models.TextField(blank=True, help_text="List of observed symptoms"),
                ),
                (
                    "affected_birds_count",
                    models.IntegerField(
                        default=0, help_text="Number of birds showing symptoms"
                    ),
                ),
                (
                    "affected_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("reduced_feed_intake", models.BooleanField(default=False)),
                ("reduced_water_intake", models.BooleanField(default=False)),
                ("respiratory_distress", models.BooleanField(default=False)),
                ("diarrhea", models.BooleanField(default=False)),
                ("swollen_eyes", models.BooleanField(default=False)),
                ("lethargy", models.BooleanField(default=False)),
                ("sudden_death", models.BooleanField(default=False)),
                (
                    "temperature_c",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "humidity_percent",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "ammonia_level",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "litter_condition",
                    models.CharField(
                        choices=[
                            ("DRY", "Dry - Good"),
                            ("DAMP", "Damp - Needs Attention"),
                            ("WET", "Wet - Change Required"),
                            ("POOR", "Poor - Immediate Action"),
                        ],
                        default="DRY",
                        max_length=20,
                    ),
                ),
                ("observations", models.TextField(blank=True)),
                ("vet_recommendations", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_records",
                        to="farm.flockbatch",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="health_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_records",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-record_date"],
            },
        ),
        migrations.CreateModel(
            name="TreatmentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "treatment_type",
                    models.CharField(
                        choices=[
                            ("MEDICATION", "Medication"),
                            ("VACCINATION", "Vaccination"),
                            ("DEWORMING", "Deworming"),
                            ("ISOLATION", "Isolation/Quarantine"),
                            ("CULLING", "Culling"),
                            ("SUPPORTIVE", "Supportive Care"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "medication_name",
                    models.CharField(
                        blank=True, help_text="Name of medication used", max_length=200
                    ),
                ),
                ("active_ingredient", models.CharField(blank=True, max_length=200)),
                (
                    "dosage",
                    models.CharField(
                        blank=True, help_text="Dosage amount", max_length=100
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ml", "Milliliters"),
                            ("mg", "Milligrams"),
                            ("g", "Grams"),
                            ("tablet", "Tablet"),
                            ("capsule", "Capsule"),
                            ("drop", "Drop"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "administration_method",
                    models.CharField(
                        choices=[
                            ("DRINKING_WATER", "Drinking Water"),
                            ("FEED", "Mixed in Feed"),
                            ("INJECTION", "Injection"),
                            ("TOPICAL", "Topical Application"),
                            ("ORAL", "Oral/Drenching"),
                            ("SPRAY", "Spray"),
                        ],
                        default="DRINKING_WATER",
                        max_length=20,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Twice daily, Once daily",
                        max_length=100,
                    ),
                ),
                (
                    "duration_days",
                    models.IntegerField(
                        default=1, help_text="Duration of treatment in days"
                    ),
                ),
                (
                    "quantity_treated",
                    models.IntegerField(default=0, help_text="Number of birds treated"),
                ),
                (
                    "total_quantity_used",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total medication used",
                        max_digits=10,
                    ),
                ),
                ("start_date", models.DateField(default=django.utils.timezone.now)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "cost_per_unit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "effectiveness_rating",
                    models.IntegerField(
                        choices=[
                            (0, "Not Rated"),
                            (1, "Poor - No improvement"),
                            (2, "Fair - Slight improvement"),
                            (3, "Good - Moderate improvement"),
                            (4, "Very Good - Significant improvement"),
                            (5, "Excellent - Full recovery"),
                        ],
                        default=0,
                    ),
                ),
                ("effectiveness_notes", models.TextField(blank=True)),
                (
                    "withdrawal_days",
                    models.IntegerField(
                        default=0, help_text="Days to withdraw before sale/consumption"
                    ),
                ),
                ("withdrawal_notes", models.TextField(blank=True)),
                ("birds_recovered", models.IntegerField(default=0)),
                ("birds_died", models.IntegerField(default=0)),
                (
                    "recovery_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "prescribed_by",
                    models.CharField(
                        blank=True, help_text="Veterinarian name", max_length=200
                    ),
                ),
                ("prescription_number", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "administered_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="administered_treatments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="treatment_records",
                        to="farm.flockbatch",
                    ),
                ),
                (
                    "health_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="treatments",
                        to="farm.healthrecord",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="treatment_records",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.AddIndex(
            model_name="healthrecord",
            index=models.Index(
                fields=["batch", "record_date"], name="farm_health_batch_i_a74d58_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="healthrecord",
            index=models.Index(
                fields=["health_status"], name="farm_health_health__f185fa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="treatmentrecord",
            index=models.Index(
                fields=["batch", "start_date"], name="farm_treatm_batch_i_73706b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="treatmentrecord",
            index=models.Index(
                fields=["treatment_type"], name="farm_treatm_treatme_53b77a_idx"
            ),
        ),
    ]
