# Generated by Django 6.0.5 on 2026-06-03 14:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0005_healthalert_healthrecord_treatmentrecord_and_more"),
        ("tenants", "0002_tenant_max_farms_tenant_max_users_tenant_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Feed Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FeedConsumption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "morning_feed_kg",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "afternoon_feed_kg",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "evening_feed_kg",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_daily_consumption",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "feed_given_kg",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "feed_remaining_kg",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "feed_wasted_kg",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "cost_per_kg",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "daily_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("bird_count", models.IntegerField(default=0)),
                (
                    "feed_per_bird_grams",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed_consumption",
                        to="farm.flockbatch",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed_consumption",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="feed_consumption_record",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="daily_record",
                to="farm.feedconsumption",
            ),
        ),
        migrations.CreateModel(
            name="FeedConsumptionAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alert_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Information"),
                            ("WARNING", "Warning"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="INFO",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "recommended_feed_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "current_consumption_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed_alerts",
                        to="farm.flockbatch",
                    ),
                ),
            ],
            options={
                "ordering": ["-alert_date"],
            },
        ),
        migrations.CreateModel(
            name="FeedInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_number", models.CharField(blank=True, max_length=100)),
                (
                    "current_stock_kg",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "minimum_stock_kg",
                    models.DecimalField(decimal_places=2, default=100, max_digits=12),
                ),
                (
                    "reorder_level_kg",
                    models.DecimalField(decimal_places=2, default=200, max_digits=12),
                ),
                ("last_purchase_date", models.DateField(blank=True, null=True)),
                (
                    "last_purchase_quantity_kg",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "last_purchase_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "average_cost_per_kg",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("supplier_name", models.CharField(blank=True, max_length=200)),
                ("supplier_contact", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed_inventory",
                        to="tenants.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FeedType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "feed_stage",
                    models.CharField(
                        choices=[
                            ("STARTER", "Starter (0-4 weeks)"),
                            ("GROWER", "Grower (4-16 weeks)"),
                            ("FINISHER", "Finisher (16+ weeks)"),
                            ("LAYER_MASH", "Layer Mash"),
                            ("BROILER_STARTER", "Broiler Starter (0-3 weeks)"),
                            ("BROILER_FINISHER", "Broiler Finisher (3-6 weeks)"),
                            ("CHICK_MASH", "Chick Mash"),
                            ("DUAL_PURPOSE", "Dual Purpose Feed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "protein_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "energy_mj_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "fat_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "fiber_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="farm.feedcategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FeedPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("purchase_date", models.DateField(default=django.utils.timezone.now)),
                ("invoice_number", models.CharField(blank=True, max_length=100)),
                ("quantity_kg", models.DecimalField(decimal_places=2, max_digits=12)),
                ("cost_per_kg", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("supplier_name", models.CharField(max_length=200)),
                ("supplier_contact", models.CharField(blank=True, max_length=100)),
                ("delivery_date", models.DateField(blank=True, null=True)),
                ("delivery_notes", models.TextField(blank=True)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("PAID", "Paid"),
                            ("PENDING", "Pending"),
                            ("PARTIAL", "Partial"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "receipt",
                    models.FileField(blank=True, null=True, upload_to="feed/receipts/"),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inventory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to="farm.feedinventory",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed_purchases",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "feed_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="farm.feedtype"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="feedinventory",
            name="feed_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="farm.feedtype"
            ),
        ),
        migrations.AddField(
            model_name="feedconsumption",
            name="feed_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="farm.feedtype"
            ),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="feed_type_obj",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="daily_records",
                to="farm.feedtype",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="feedinventory",
            unique_together={("tenant", "feed_type", "batch_number")},
        ),
        migrations.CreateModel(
            name="FeedingGuide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bird_type",
                    models.CharField(
                        choices=[
                            ("LAYERS", "Layers"),
                            ("BROILERS", "Broilers"),
                            ("KUROILERS", "Kuroilers"),
                        ],
                        max_length=20,
                    ),
                ),
                ("week_start", models.IntegerField(help_text="Starting week")),
                ("week_end", models.IntegerField(help_text="Ending week")),
                (
                    "daily_feed_per_bird_grams",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Daily feed per bird in grams",
                        max_digits=8,
                    ),
                ),
                (
                    "expected_weight_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "expected_egg_production",
                    models.IntegerField(
                        blank=True,
                        help_text="Expected eggs per day per 100 birds",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "feed_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="farm.feedtype"
                    ),
                ),
            ],
            options={
                "ordering": ["bird_type", "week_start"],
                "unique_together": {("bird_type", "week_start", "week_end")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="feedconsumption",
            unique_together={("batch", "date", "feed_type")},
        ),
    ]
