# Generated by Django 6.0.5 on 2026-06-03 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0006_feedcategory_feedconsumption_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dailyrecord",
            name="feed_consumption_record",
        ),
        migrations.AddField(
            model_name="feedconsumption",
            name="daily_record",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="feed_consumption_record",
                to="farm.dailyrecord",
            ),
        ),
    ]
