# Generated by Django 6.0.5 on 2026-06-03 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0007_remove_dailyrecord_feed_consumption_record_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedconsumption",
            name="cost_per_kg",
        ),
    ]
