# Generated by Django 6.0.5 on 2026-06-04 15:17

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0008_remove_feedconsumption_cost_per_kg"),
        ("tenants", "0002_tenant_max_farms_tenant_max_users_tenant_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feedconsumption",
            options={"ordering": ["-date", "-created_at"]},
        ),
        migrations.AlterUniqueTogether(
            name="feedconsumption",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="feedconsumption",
            name="feed_amount_kg",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="feedconsumption",
            name="feeding_time",
            field=models.CharField(
                choices=[
                    ("MORNING", "Morning (6:00 - 10:00)"),
                    ("AFTERNOON", "Afternoon (12:00 - 15:00)"),
                    ("EVENING", "Evening (17:00 - 20:00)"),
                ],
                default="MORNING",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="feedconsumption",
            index=models.Index(
                fields=["batch", "date", "feeding_time"],
                name="farm_feedco_batch_i_e5194e_idx",
            ),
        ),
        migrations.RemoveField(
            model_name="feedconsumption",
            name="afternoon_feed_kg",
        ),
        migrations.RemoveField(
            model_name="feedconsumption",
            name="daily_cost",
        ),
        migrations.RemoveField(
            model_name="feedconsumption",
            name="evening_feed_kg",
        ),
        migrations.RemoveField(
            model_name="feedconsumption",
            name="morning_feed_kg",
        ),
        migrations.RemoveField(
            model_name="feedconsumption",
            name="total_daily_consumption",
        ),
    ]
