# Generated by Django 6.0.5 on 2026-06-05 12:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0009_alter_feedconsumption_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedconsumption",
            name="feed_amount_kg",
        ),
        migrations.AddField(
            model_name="feedconsumption",
            name="current_stock_kg",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="feedconsumption",
            name="feed_consumed_kg",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
    ]
