# Generated by Django 6.0.5 on 2026-06-05 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0010_remove_feedconsumption_feed_amount_kg_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedconsumption",
            name="daily_record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="feed_consumption_records",
                to="farm.dailyrecord",
            ),
        ),
    ]
