# Generated by Django 6.0.5 on 2026-06-05 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0011_alter_feedconsumption_daily_record"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedconsumption",
            name="daily_record",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="feed_consumption_record",
                to="farm.dailyrecord",
            ),
        ),
    ]
