# Generated by Django 6.0.5 on 2026-06-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0013_alter_feedconsumption_daily_record"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flockbatch",
            name="status",
            field=models.CharField(
                choices=[
                    ("PLANNED", "Planned"),
                    ("ACTIVE", "Active"),
                    ("COMPLETED", "Completed"),
                    ("CULLED", "Culled"),
                    ("DEPLETED", "Depleted"),
                    ("SICK", "Sick/Quarantined"),
                ],
                default="PLANNED",
                max_length=20,
            ),
        ),
    ]
