# Generated by Django 6.0.5 on 2026-06-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0014_alter_flockbatch_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farm",
            name="registration_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
