# Generated by Django 6.0.5 on 2026-06-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farm", "0015_alter_farm_registration_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="vaccinationrecord",
            name="vaccine_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="vaccinationrecord",
            name="vaccine_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NEWCASTLE", "Newcastle Disease (ND)"),
                    ("INFECTIOUS_BRONCHITIS", "Infectious Bronchitis (IB)"),
                    ("GUMBORO", "Gumboro (IBD)"),
                    ("FOWL_POX", "Fowl Pox (FP)"),
                    ("SALMONELLA", "Salmonella"),
                    ("COCCIDIOSIS", "Coccidiosis"),
                    ("MAREKS", "Marek's Disease"),
                    ("EGG_DROP_SYNDROME", "Egg Drop Syndrome"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=30,
            ),
        ),
    ]
