# Generated by Django 6.0.5 on 2026-06-11 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0002_tenant_max_farms_tenant_max_users_tenant_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Training",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "training_type",
                    models.CharField(
                        choices=[
                            ("POULTRY_HEALTH", "Poultry Health Management"),
                            ("FEED_FORMULATION", "Feed Formulation"),
                            ("RECORD_KEEPING", "Record Keeping"),
                            ("BREEDING", "Breeding Techniques"),
                            ("MARKETING", "Marketing & Sales"),
                            ("BIO_SECURITY", "Bio-security"),
                            ("WASTE_MANAGEMENT", "Waste Management"),
                            ("BUSINESS_SKILLS", "Business Skills"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "topics_covered",
                    models.TextField(
                        blank=True, help_text="List of topics to be covered"
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("venue", models.CharField(max_length=255)),
                ("district", models.CharField(blank=True, max_length=100)),
                ("village", models.CharField(blank=True, max_length=100)),
                ("gps_coordinates", models.CharField(blank=True, max_length=100)),
                ("trainer_name", models.CharField(max_length=200)),
                ("trainer_contact", models.CharField(blank=True, max_length=20)),
                ("trainer_email", models.EmailField(blank=True, max_length=254)),
                ("trainer_organization", models.CharField(blank=True, max_length=200)),
                ("expected_participants", models.IntegerField(default=0)),
                ("actual_participants", models.IntegerField(default=0)),
                (
                    "materials_provided",
                    models.TextField(
                        blank=True,
                        help_text="List of materials/training materials provided",
                    ),
                ),
                (
                    "budget",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "actual_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UPCOMING", "Upcoming"),
                            ("ONGOING", "Ongoing"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="UPCOMING",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("feedback_summary", models.TextField(blank=True)),
                (
                    "average_rating",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_training_programs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "farmers",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={"role": "FARMER"},
                        related_name="training_programs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trainings",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="TrainingAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attendance_status",
                    models.CharField(
                        choices=[
                            ("PRESENT", "Present"),
                            ("ABSENT", "Absent"),
                            ("LATE", "Late"),
                            ("EXCUSED", "Excused"),
                        ],
                        default="PRESENT",
                        max_length=20,
                    ),
                ),
                ("check_in_time", models.DateTimeField(blank=True, null=True)),
                ("check_out_time", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_attendance_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "training",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="trainings.training",
                    ),
                ),
            ],
            options={
                "ordering": ["training", "-check_in_time"],
            },
        ),
        migrations.CreateModel(
            name="TrainingEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_rating",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        help_text="Rating for training content",
                    ),
                ),
                (
                    "trainer_rating",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        help_text="Rating for trainer effectiveness",
                    ),
                ),
                (
                    "materials_rating",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        help_text="Rating for training materials",
                    ),
                ),
                (
                    "venue_rating",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        help_text="Rating for venue/facilities",
                    ),
                ),
                (
                    "overall_rating",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        help_text="Overall satisfaction rating",
                    ),
                ),
                ("what_was_good", models.TextField(blank=True)),
                ("what_needs_improvement", models.TextField(blank=True)),
                ("suggestions", models.TextField(blank=True)),
                ("would_recommend", models.BooleanField(default=True)),
                ("interested_in_follow_up", models.BooleanField(default=False)),
                ("follow_up_topic", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_evaluations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "training",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="trainings.training",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="training",
            index=models.Index(fields=["status"], name="trainings_t_status_8ebfec_idx"),
        ),
        migrations.AddIndex(
            model_name="training",
            index=models.Index(
                fields=["start_date"], name="trainings_t_start_d_1d6954_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="training",
            index=models.Index(
                fields=["tenant", "status"], name="trainings_t_tenant__3cf2cf_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="trainingattendance",
            unique_together={("training", "farmer")},
        ),
        migrations.AlterUniqueTogether(
            name="trainingevaluation",
            unique_together={("training", "farmer")},
        ),
    ]
